# Generated by Django 4.1 on 2022-09-18 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientunitstayid', models.IntegerField()),
                ('gender', models.CharField(default=None, max_length=25, null=True)),
                ('age', models.CharField(default=None, max_length=10, null=True)),
                ('admissionheight', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('admissionweight', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('dischargeweight', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('apachescore', models.IntegerField(default=None, null=True)),
                ('unitdischargestatus', models.CharField(choices=[('Alive', 'Alive'), ('Expired', 'Expired')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='VitalPeriodic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saO2', models.IntegerField(default=None, null=True)),
                ('heartRate', models.IntegerField(default=None, null=True)),
                ('respiration', models.IntegerField(default=None, null=True)),
                ('systemicSystolic', models.IntegerField(default=None, null=True)),
                ('systemicDiastolic', models.IntegerField(default=None, null=True)),
                ('systemicMean', models.IntegerField(default=None, null=True)),
                ('observationOffset', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='RespiratoryCharting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respChartValueLabel', models.CharField(max_length=255)),
                ('respChartValue', models.CharField(default=None, max_length=1000, null=True)),
                ('respChartOffset', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labName', models.CharField(default=None, max_length=255, null=True)),
                ('labResult', models.DecimalField(decimal_places=4, default=None, max_digits=11, null=True)),
                ('labResultOffset', models.IntegerField(default=None, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='IntakeOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intakeTotal', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True)),
                ('outputTotal', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True)),
                ('dialysisTotal', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True)),
                ('netTotal', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True)),
                ('intakeOutputOffset', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
